### ISSUE TITLE
can this be profiled?

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/dunnaslian#2]
Note lexibank 2.1 is in PR #1

This already has an orthography profile -- does it need revising or checking?

**Comment by SimonGreenhill** [comment]
Note lexibank 2.1 is in PR #1

**Comment by LinguList** [comment]
yes, you should add "()[]" to the form spec, though. And if you look at the bottom of the profile, you may find some other nasty things that can be excluded in that stage...

**Comment by SimonGreenhill** [comment]
Ok, i've culled the mess in the profile. Not sure what you mean abotu the []()? it's already there in strip brackets?

**Comment by LinguList** [comment]
see #3

**Comment by SimonGreenhill** [comment]
Danke! Closing in favor of #3
