### ISSUE TITLE
Orthography Profile of Aslian Languages

### ISSUE THREAD

**Issue by LinguList** [lexibank/dunnaslian#3]
We need the help of @evoling, since the internet does not provide sufficient information on the interpretation of consonant clusters and many sounds in Aslian languages.

Major questions include:

* is [c](https://clts.clld.org/parameters/voiceless_palatal_stop_consonant) really a voiceless palatal stop?
* how do I interpret sequences such as `bh` in the data? Does `h` mark aspiration here, and if so, is the aspiration plain, breathy-voiced, etc., or what?
* likewise `nh`, we have sequences such as `cnhɛt`, is the `n` syllabic here? Is the `h` marking the articulation of the `n` or a sound of itself?

Maybe, @evoling could have a look at the data to help here? Specifically our [orthography profile](https://github.com/lexibank/dunnaslian/blob/master/etc/orthography.tsv).

**Comment by evoling** [comment]
I have forwarded these questions to the Aslian scholars, and will get back to you. Michael/@evoling

**Comment by SimonGreenhill** [comment]
Thanks Michael! Hope you're winding down for the year!

**Comment by evoling** [comment]
Hej allihopa!

- The c really is a voiceless palatal stop.
- Sequences of Ch (e.g. bh, nh) are really just sequences of phonemes. Aslian languages are very generous with what they allow in a syllable-initial cluster. Individual languages have various epenthesis rules for syllabification, but lexibank doesn't syllabify things, so that should be unnecessary.

Hälsningar, Michael

--
Michael Dunn, Professor of General Linguistics
Department of Linguistics and Philology, Uppsala University
+46 18 4711341 @MishaDunn http://evoling.net

> On 2 Dec 2019, at 11:02, Johann-Mattis List <notifications@github.com> wrote:
>
> We need the help of @evoling, since the internet does not provide sufficient information on the interpretation of consonant clusters and many sounds in Aslian languages.
>
> Major questions include:
>
> • is c really a voiceless palatal stop?
> • how do I interpret sequences such as bh in the data? Does h mark aspiration here, and if so, is the aspiration plain, breathy-voiced, etc., or what?
> • likewise nh, we have sequences such as cnhɛt, is the n syllabic here? Is the h marking the articulation of the n or a sound of itself?
> Maybe, @evoling could have a look at the data to help here? Specifically our orthography profile.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>









När du har kontakt med oss på Uppsala universitet med e-post så innebär det att vi behandlar dina personuppgifter. För att läsa mer om hur vi gör det kan du läsa här: http://www.uu.se/om-uu/dataskydd-personuppgifter/

E-mailing Uppsala University means that we will process your personal data. For more information on how this is performed, please read here: http://www.uu.se/en/about-uu/data-protection-policy

**Comment by LinguList** [comment]
Thanks a lot, @evoling, just to clarify: there are really NO contrasts in terms of aspirated vs. unaspirated, right? So we can really interprete the instances as literally ipa elements. That's making it vor us a lot easier, but it shows how important it is to ask about it as well...

**Comment by evoling** [comment]
Not quite! Some of these languages have three way VOT contrasts, but in that case aspiration is marked with superscript h. Cheers, M

> On 2 Dec 2019, at 17:28, Johann-Mattis List <notifications@github.com> wrote:
>
> Thanks a lot, @evoling, just to clarify: there are really NO contrasts in terms of aspirated vs. unaspirated, right? So we can really interprete the instances as literally ipa elements. That's making it vor us a lot easier, but it shows how important it is to ask about it as well...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>









När du har kontakt med oss på Uppsala universitet med e-post så innebär det att vi behandlar dina personuppgifter. För att läsa mer om hur vi gör det kan du läsa här: http://www.uu.se/om-uu/dataskydd-personuppgifter/

E-mailing Uppsala University means that we will process your personal data. For more information on how this is performed, please read here: http://www.uu.se/en/about-uu/data-protection-policy

**Comment by LinguList** [comment]
BTW, with respect to syllabification: we do not syllabify, since scholars usually don't. Our CLDF format is capable of rendering syllabification, but it would need to come in an extra slot indicating where in the segmentized version of the sequence the breaks are. This is much safer than placing information into the sequence itself, as the information is of course suprasegmental... So if this information is available for the data, we'd definitely be interested in adding it.

**Comment by tresoldi** [comment]
Ops, forgot to update the metadata title according to the new standard. I'll do it and push to master.
